version: '3.4'
services:
  frontend-vue:
    container_name: frontend
    image: node:lts
    working_dir: /app
    ports:
      - 8001:8000
    depends_on:
      - backend-laravel
    entrypoint: /bin/sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app

  backend-laravel:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./start.sh --serve
    ports:
      - 8002:8000
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html

  redis:
    image: redis:latest

  queue-worker:
    container_name: queue
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/var/www/html
    command: ./start.sh --queue

  scheduler:
    container_name: scheduler
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/var/www/html
    command: ./start.sh --schedule

  db:
    image: mysql:8.0
    env_file: './.env'
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8003:80
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit
    container_name: mailer
    ports:
      - "1025:1025"
      - "8004:8025"

volumes:
  db_data: